### ISSUE TITLE
Error when deleting a product with more than 1 review

### ISSUE THREAD

**Issue by leflings** [Sylius/Sylius#10659]
**Sylius version affected**: 1.5.3|1.6.0

I've just tested this on multiple local installations, aswell as on demo.sylius.com.

**Description**  
When you attempt to delete a product that has *more than 1* reviews, an error is thrown by doctrine. Something a long the lines of `Notice: Undefined index: 0000000016265c10000000006e1f1467`.

**Steps to reproduce**  
1. Create a new product
2. Add two or more reviews to it
3. Attempt to delete product (same result via admin, admin api, or straight from code)

(as of writing this bug can be observed by trying to delete [this product](https://demo.sylius.com/admin/products/303944/edit))

**Comment by maximehuran** [comment]
This issue still exists

**Comment by Zales0123** [comment]
Sorry guys for the **really** long response time. Indeed, there is a bug, we should fix it 👍

**Comment by chadyred** [comment]
Hello, ce bug est toujours présent, depuis un bon moment, des nouvelles sur ce dernier ?

**Comment by ikanaweb** [comment]
I found a workaround to prevent this error.

The issue comes from `\Sylius\Bundle\ReviewBundle\EventListener\ReviewChangeListener::postRemove` called on each removed `ReviewInterface`.
This method calls `\Sylius\Bundle\ReviewBundle\Updater\AverageRatingUpdater::modifyReviewSubjectAverageRating` which in the end calls `flush` again.

I'm not sure how it happens but in the end the `Product` entity we want to be removed still has references to `ProductReview` items which are not attached anymore to the entitymanager.

I decorated `sylius.listener.product_review_change` with my own listener to override `postRemove` and store in a property the `ReviewableInterface` subjects that needs to be updated by `ReviewableRatingUpdaterInterface`, and finally update them in `postFlush` event. 
There may be an another way to fix this issue but it works.

**Comment by Rafikooo** [comment]
Hello @leflings,

since this problem still exists, we decided to put it in the backlog, it should be fixed in some time 💃 

Greetings,
Rafał 🚀

**Comment by Rafikooo** [comment]
I tested on Sylius 1.14 and 2.1 and can no longer reproduce the issue. I’m not sure what changed—perhaps a cascade removal was introduced. I found this: https://github.com/Sylius/Sylius/pull/17139/files#diff-8e53aad9d7049da2f370c490fb36c8f7ef2ee6b5957c4cce4ce470407eb3641eR52, but reverting those changes didn’t make a difference. I’m closing this for now; if I missed something, please feel free to reopen. 💃
