### ISSUE TITLE
Failure during installation process

### ISSUE THREAD

**Issue by kenkataiwa** [Sylius/Sylius#2604]
There is a problem with the installation process it fails here:

Fatal error: Uncaught exception 
'Symfony\Component\Filesystem\Exception\IOException' with message 'Cannot rename "<path\to\>\sylius\app\cache\de_" to "<path\to\>\sylius\app\cache\dev".' in <path\to\>\sylius\vendor\symfony\symfony\src\Symfony\Component\Filesystem\Filesystem.php:262

Even when I do: php app/console cache:clear I get the same "Cannot rename" error

**Comment by pjedrzejewski** [comment]
@kenkataiwa This is something wrong with your filesystem permissions. http://symfony.com/doc/current/book/installation.html#book-installation-permissions

**Comment by kenkataiwa** [comment]
@pjedrzejewski it's not a permissions issue because I'm on a Windows system and have full access to the account I'm using so I am able to write to that directory. It might be something do with Symfony caching in general, or on Sylius maybe. But I think it's an issue that's why I raised it here.

Because if I do "php app/console cache:clear" it fails but when I do: "php app/console cache:clear --no-warmup" it works.

**Comment by pjedrzejewski** [comment]
You are right, I recall this issue... I remember someone had it already with older version of Sylius. What version are you using?

**Comment by kenkataiwa** [comment]
It's the very latest because I did "composer create-project sylius/sylius" today. 
I've looked at the composer.json it says: 0.14-dev
![capture](https://cloud.githubusercontent.com/assets/2436107/6734940/13ce645c-ce6c-11e4-82a2-555b3e277fd7.PNG)

**Comment by AlexisBarat** [comment]
Hi, i've the same issue here, using 0.14.*@dev.
Anyone found the solution ?

**Comment by hantsy** [comment]
I have encountered the same problem in 0.14-dev.

**Comment by hantsy** [comment]
$ php app/console sylius:install
Installing Sylius...

Step 1 of 4. Checking system requirements.
+------------------------------------+------------------------------------+
| Issue                              | Recommendation                     |
+------------------------------------+------------------------------------+
| sylius.settings.short_open_tag     |                                    |
| sylius.settings.session.auto_start |                                    |
| sylius.extensions.accelerator      | sylius.extensions.accelerator.help |
+------------------------------------+------------------------------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.



  [Symfony\Component\Filesystem\Exception\IOException]
  Cannot rename "E:\temp\sylius-standard\app\cache\de_" to "E:\temp\sylius-st
  andard\app\cache\dev".



cache:clear [--no-warmup] [--no-optional-warmers]

**Comment by hantsy** [comment]
If I create the project without `-s dev`，the 0.13 will be used, and ｉｔ works.

**Comment by bertinl** [comment]
Well if you try
 php app/console sylius:install -e prod

it gives the same error as it uses 0.14-dev also

**Comment by Hunternnm** [comment]
> I:\xampp\php\php.exe I:\xampp\htdocs\sylius.loc\app\console sylius:install
Installing Sylius...

Step 1 of 4. Checking system requirements.
+------------------------------------+------------------------------------+
| Issue                              | Recommendation                     |
+------------------------------------+------------------------------------+
| sylius.settings.short_open_tag     |                                    |
| sylius.settings.session.auto_start |                                    |
| sylius.extensions.intl             | sylius.extensions.help             |
| sylius.extensions.accelerator      | sylius.extensions.accelerator.help |
+------------------------------------+------------------------------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.


                                                                               
  [Symfony\Component\Filesystem\Exception\IOException]                         
  Cannot rename "I:\xampp\htdocs\sylius.loc\app\cache\de_" to "I:\xampp\htdoc  
  s\sylius.loc\app\cache\dev".                                                 
                                                                               


cache:clear [--no-warmup] [--no-optional-warmers]



Process finished with exit code 0 at 09:50:44.
Execution time: 62 104 ms.

> I:\xampp\php\php.exe I:\xampp\htdocs\sylius.loc\app\console sylius:install -s

      _____                  __
     / ____|                / _|
    | (___  _   _ _ __ ___ | |_ ___  _ __  _   _
     \___ \| | | | '_ ` _ \|  _/ _ \| '_ \| | | |
     ____) | |_| | | | | | | || (_) | | | | |_| |
    |_____/ \__, |_| |_| |_|_| \___/|_| |_|\__, |
             __/ |                          __/ |
            |___/                          |___/


Welcome to the Symfony shell (2.6.6 - app/dev/debug).

At the prompt, type help for some help,
or list to get a list of available commands.

To exit the shell, type ^D.

Symfony > sylius:install
Installing Sylius...

Step 1 of 4. Checking system requirements.
+------------------------------------+------------------------------------+
| Issue                              | Recommendation                     |
+------------------------------------+------------------------------------+
| sylius.settings.short_open_tag     |                                    |
| sylius.settings.session.auto_start |                                    |
| sylius.extensions.intl             | sylius.extensions.help             |
| sylius.extensions.accelerator      | sylius.extensions.accelerator.help |
+------------------------------------+------------------------------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.


                                                                               
  [Symfony\Component\Filesystem\Exception\IOException]                         
  Cannot rename "I:\xampp\htdocs\sylius.loc\app\cache\de_" to "I:\xampp\htdoc  
  s\sylius.loc\app\cache\dev".                                                 
                                                                               


cache:clear [--no-warmup] [--no-optional-warmers]



Process finished with exit code 0 at 09:52:24.
Execution time: 71 173 ms.

Sylius 0.13 stable...

**Comment by myspulin** [comment]
Hi, have the same issue, is there any solution? it's definitely not a permissions problem I use windows system and have all needed rights.

Thanks for help.

**Comment by aguerre** [comment]
Working with 0.13 for me, on windows.

**Comment by payalord** [comment]
Anytime when i trying to install any version of Sylius, i'm getting an errors. Wasn't been able to install any version fine yet. 0.13 version have some PHP fatal errors on "sylius:install" as well as 0.14, but 0.14 is dev version, i can understand that.

**Comment by aguerre** [comment]
What's the errors ? Maybe there is bad parameters in your php.ini

**Comment by payalord** [comment]
Yes, not enough components was "on" in php.ini + installed v0.13.0 stable everything is fine now. As i understand v0.14 still in development and not stable yet.

**Comment by payalord** [comment]
I think this must be described in docs on installation page. And maybe noticed on the website on "Get started" page. That must be clear and described what the current stable version and what the current development version. Which steps exactly need to be done to install with no problems the stable version. And which steps need to be done to install the dev version and what problems can be faced during the installation of dev and the steps what need to do to fix that problems themselves. Those people who are new to the composer/symfony/sylius can face an installation problems and don't know exactly what to do, to avoid the problems with installation. In the case they want just to check, is this e-commerce solution good or not for them, they will face errors right already on installation process, that they never experienced in other e-commerce solution installation steps. They can go away with thoughts that Sylius is not so good, if they have problems already on installation then what can they expect from Sylius after that?

**Comment by dmidz** [comment]
Well I am also facing a failed install while I follow the instructions at http://sylius.org/get-started :
>php app/console sylius:install
Installing Sylius...

Step 1 of 4. Checking system requirements.
+-------------------------------+-----------------------------------------------
----------------------+
| Issue                         | Recommendation
                      |
+-------------------------------+-----------------------------------------------
----------------------+
| short_open_tag                |
                      |
| session.auto_start            |
                      |
| sylius.extensions.accelerator | Install and enable a PHP accelerator like APC
(highly recommended). |
+-------------------------------+-----------------------------------------------
----------------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.
The command terminated with an error code: 1.
  [Exception]
  The command terminated with an error code: 1.

.................................................................................
Firstly few things does not work as is :
- config_dev.yml uses
        #dbname: %sylius.database.name%_dev
        dbname: %sylius.database.name%
so it would work with what I typed in CLI inputs
- then I got error like
  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: ini_set(): A session is active. You cannot change the session modu
  le's ini settings at this time
So I had to change config.yml
    #session:         ~
    session:
        storage_id: session.storage.php_bridge
        handler_id: ~

And finally I am getting an error code 1 and no tables installed, this is a pitty, I am trying to test this promising eshop framework !
I tried few times, installation is too much time consume, here are some errors I get in the log :
........................................................................................
[2015-07-21 16:43:45] translation.WARNING: Translation not found. {"id":"sylius.settings","domain":"requirements","locale":"en_US"} []
[2015-07-21 16:43:45] translation.DEBUG: Translation use fallback catalogue. {"id":"sylius.settings.on","domain":"requirements","locale":"en_US"} []
[2015-07-21 16:43:45] translation.DEBUG: Translation use fallback catalogue. {"id":"sylius.settings.off","domain":"requirements","locale":"en_US"} []
...... last events before commands terminated
[2015-07-21 16:47:13] php.DEBUG: "Symfony\Component\Console\Helper\TableHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\Table" instead. {"type":16384,"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Helper\\HelperSet.php","line":86,"level":4352} []
[2015-07-21 16:47:13] event.DEBUG: Notified event "console.terminate" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate". [] []
[2015-07-21 16:47:13] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". [] []
[2015-07-21 16:47:15] doctrine.DEBUG: SHOW DATABASES [] []
[2015-07-21 16:47:15] php.DEBUG: "Symfony\Component\Console\Helper\ProgressHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\ProgressBar" instead. {"type":16384,"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Helper\\HelperSet.php","line":84,"level":4352} []
[2015-07-21 16:47:15] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". [] []
[2015-07-21 16:47:16] event.DEBUG: Notified event "console.terminate" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate". [] []
[2015-07-21 16:47:16] event.DEBUG: Notified event "console.terminate" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate". [] []
[2015-07-21 16:47:16] event.DEBUG: Notified event "console.terminate" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate". [] []
[2015-07-21 16:47:16] php.CRITICAL: Uncaught Exception: The command terminated with an error code: 1. {"type":1,"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\sylius\\sylius\\src\\Sylius\\Bundle\\InstallerBundle\\Command\\CommandExecutor.php","line":81,"level":16383,"stack":[{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\sylius\\sylius\\src\\Sylius\\Bundle\\InstallerBundle\\Command\\AbstractInstallCommand.php","line":122,"function":"runCommand","class":"Sylius\\Bundle\\InstallerBundle\\Command\\CommandExecutor","type":"->","args":["doctrine:database:create",[]]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\sylius\\sylius\\src\\Sylius\\Bundle\\InstallerBundle\\Command\\InstallDatabaseCommand.php","line":50,"function":"runCommands","class":"Sylius\\Bundle\\InstallerBundle\\Command\\AbstractInstallCommand","type":"->","args":[["doctrine:database:create","doctrine:schema:create","cache:clear","doctrine:phpcr:repository:init"],"[object] (Symfony\\Component\\Console\\Input\\ArrayInput: \"sylius:install:database\" --no-debug=1 --env=dev)","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Command\\Command.php","line":259,"function":"execute","class":"Sylius\\Bundle\\InstallerBundle\\Command\\InstallDatabaseCommand","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArrayInput: \"sylius:install:database\" --no-debug=1 --env=dev)","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Application.php","line":886,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArrayInput: \"sylius:install:database\" --no-debug=1 --env=dev)","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Application.php","line":195,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":["[object] (Sylius\\Bundle\\InstallerBundle\\Command\\InstallDatabaseCommand: {})","[object] (Symfony\\Component\\Console\\Input\\ArrayInput: \"sylius:install:database\" --no-debug=1 --env=dev)","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Console\\Application.php","line":96,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArrayInput: \"sylius:install:database\" --no-debug=1 --env=dev)","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Application.php","line":126,"function":"doRun","class":"Symfony\\Bundle\\FrameworkBundle\\Console\\Application","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArrayInput: \"sylius:install:database\" --no-debug=1 --env=dev)","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\sylius\\sylius\\src\\Sylius\\Bundle\\InstallerBundle\\Command\\CommandExecutor.php","line":74,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArrayInput: \"sylius:install:database\" --no-debug=1 --env=dev)","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\sylius\\sylius\\src\\Sylius\\Bundle\\InstallerBundle\\Command\\InstallCommand.php","line":48,"function":"runCommand","class":"Sylius\\Bundle\\InstallerBundle\\Command\\CommandExecutor","type":"->","args":["sylius:install:database",[],"[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Command\\Command.php","line":259,"function":"execute","class":"Sylius\\Bundle\\InstallerBundle\\Command\\InstallCommand","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: \"sylius:install\")","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Application.php","line":886,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: \"sylius:install\")","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Application.php","line":195,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":["[object] (Sylius\\Bundle\\InstallerBundle\\Command\\InstallCommand: {})","[object] (Symfony\\Component\\Console\\Input\\ArgvInput: \"sylius:install\")","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Console\\Application.php","line":96,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: \"sylius:install\")","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Console\\Application.php","line":126,"function":"doRun","class":"Symfony\\Bundle\\FrameworkBundle\\Console\\Application","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: \"sylius:install\")","[object] (Symfony\\Component\\Console\\Output\\ConsoleOutput: {})"]},{"file":"E:\\_projects\\symfony\\sylius-standard\\app\\console","line":17,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":["[object] (Symfony\\Component\\Console\\Input\\ArgvInput: \"sylius:install\")"]}]} []
........................................................................................
Any suggestion I could try please ?

**Comment by Vishnja** [comment]
Same error.

**Comment by nakashu** [comment]
Fix/workaround here: [#3071#issuecomment-141682129](https://github.com/Sylius/Sylius/issues/3071#issuecomment-141682129)

**Comment by nakashu** [comment]
possiblem fix was merged, please confirm if problem persist

**Comment by manuelbcd** [comment]
Still facing the same problem on XAMPP

**Comment by nakashu** [comment]
@manuelbcd what version are you using.. this should be fixed bud only on master.
also if you are using xampp on linux, it would be probably permissions.
If you are using it on windows, check if you got this in your composer.json

`"sylius/sylius":                "0.16.*@dev",`

and after that try running composer update, to see if it is resolved.

**Comment by manuelbcd** [comment]
@nakashu Thanks for answering.  I'm working with Xampp on Windows.
composer.json:
        "branch-alias": {
            "dev-master": "0.13-dev"
        },

I don't' have the specific tag that you mentioned.

WBR

**Comment by nakashu** [comment]
@manuelbcd .. ok the line was if you were using [sylius/sylius-standard](https://github.com/Sylius/Sylius-Standard)  repo/installation

You are using [sylus/sylus](https://github.com/Sylius/Sylius) I guess.

You can still update your app by running `composer update`. Please backup your code (eg. to repo or hard copy), as there could be few breaking changes in update from .13-dev -> .16-dev.

If you are not able to update for any reason, a quick fix for the problem is pointing the session storage out of the cache directory like so:

This will make the session storage to fallback to use, default php location, from php.ini file

    session:
        handler_id: ~

With this you can configure the session to be stored in a directory you specify.

    session:
        save_path: %kernel.root_dir%/sessions 

But the real fix is upgrading, as there was fixed a bug, that caused this error.
More in detail you can read here: https://github.com/Sylius/Sylius/issues/3071#issuecomment-141563609 and here https://github.com/Sylius/Sylius/issues/3071#issuecomment-141682129

**Comment by manuelbcd** [comment]
Thanks again nakashu, but I still getting the same error message.

Installed 16-dev  and also tried to change session configuration in config.yaml and config_dev.yaml

I don't know why, but this does not work

**Comment by nakashu** [comment]
@manuelbcd are you using XAMPP on windows or linux ? 

## linux
If you are using it on linux, it will be probably permssion problem, and try setting permission 0777 to the cache folder.

## windows
If you are using it on windows, you can check one thing in code to see if you got the correct code base.
Look inside the file `src/Sylius/Bundle/CoreBundle/Templating/Helper/MoneyHelper.php`
on line 41 there should be `return $this->localeContext->getDefaultLocale();`
if there is current locale `return $this->localeContext->getCurrentLocale();` you are using old code.

## assetic or other processes
Another thing that happended to me when I had. running `assetic:watch`, and I tried clearing the cache. It would fail.
This can happen with other stuff like assetic, that try to do stuff inside the cache folder, like IDE indexing (exclude the folder for fix), or other watcher, indexers running in background.

After these, I don't really know what else could be the problem.

**Comment by manuelbcd** [comment]
I'm using XAMPP over Windows7.  I have checked src/Sylius/Bundle/CoreBundle/Templating/Helper/MoneyHelper.php and it's the last version. 
Tried to clean all, downloaded again with composer and installed again 0.16 version.

Still same problem ( IOException ... cannot rename ... )

**Comment by pjedrzejewski** [comment]
We need to definitely have a look at http://www.appveyor.com/.

**Comment by manuelbcd** [comment]
Hi, I have installed it today in another Win7 machine and it's working like charm!

**Comment by nakashu** [comment]
@manuelbcd good to hear, I would say that it was some process blocking the files.

@pjedrzejewski should these issues be closed? #2604(this one) and #3071 - as both where probably because of the session starting during boot.
It was fixed with #3323, and no one else mentioned it would still fail with the rename thing.

**Comment by pjedrzejewski** [comment]
@nakashu Yes, closing. Thanks for help! :)
