### ISSUE TITLE
Fatal on the homepage (dev-master)

### ISSUE THREAD

**Issue by alexchuin** [Sylius/Sylius#7527]
Hi Guys,

I've updated Sylius from BETA to dev-master.
I have the following error on the Homepage (admin and console is OK):

```
FatalThrowableError in ExceptionController.php line 43:
Type error: Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::__construct() must implement interface FOS\RestBundle\View\ViewHandlerInterface, none given, called in /code/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 202
```

Any Idea ?

Thanks !

**Comment by lchrusciel** [comment]
did you update FOR RestBundle? Also, did you work on Sylius or Sylius-Standard?

**Comment by alexchuin** [comment]
Hi, 

FOS RestBundle was updated by this commit:
https://github.com/Sylius/Sylius/commit/defa24759afd5a5857d91af2bfdcc6252589a4b8

I'm using standard edition.

Thanks for your help.

**Comment by lchrusciel** [comment]
@alexchuin can you tell me wich version of Sylius-Standard are you using? It should be fixed after [ aa46d22](https://github.com/Sylius/Sylius-Standard/commit/aa46d22e4b9797c1f60f392e805e84e20e115127)

**Comment by kurakin-oleksandr** [comment]
Try to add into `./app/config/config.yml`
```
fos_rest:
    exception: ~
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }
```

**Comment by pamil** [comment]
Only this part is required to tackle this issue:

```yaml
fos_rest:
    exception: ~
```

**Comment by pjedrzejewski** [comment]
We confirmed on Slack this ^ fixes the issue, please reopen if still a problem.
